# TLS Transport Server Configuration
server:
  tun_name: tun0
  tun_ip: 0.0.0.0
  tun_peer: 10.8.0.2
  mtu: 1400
  listen_port: 2222

forwarding:
  enable_nat: false
  enable_route: true

transport:
  type: tls
  certfile: config/certs/cert.pem
  keyfile: config/certs/key.pem

session:
  heartbeat_timeout: 30
